--- #YAML:1.0
name:               DynGig-CLI
version:            0.03
abstract:           A collection of CLI modules
author:
    - Kan Liu <kan@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Cwd:                  0
    Digest::MD5:          0
    DynGig::Automata:     1
    DynGig::Multiplex:    1
    DynGig::Range:        1
    DynGig::Range::Cluster:  0
    DynGig::RCE:          1
    DynGig::Schedule:     0
    DynGig::Util:         1
    File::Spec:           0
    File::Temp:           0
    Getopt::Long:         0
    IO::Select:           0
    Pod::Usage:           0
    POSIX:                0
    Sys::Hostname:        0
    Test::More:           0
    YAML::XS:             0.38
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
